### PR TITLE
sort entries into columns

### PR DESCRIPTION
**Pull request by joseph-belmonte**
- added location property on each food entry
- filtered entry list in each column to match that column heading location
- added some styling

### CODE REVIEW

**Comment by evening** [comment]
wow good job amazing!!!!
looks great -- could we also make this header responsive as well?? looks weird with low width
image

**Comment by joseph-belmonte** [comment]
image
Should be OK on small screen sizes now! Is there a min. limit we would consider? Some of the text columns are overlapping on very small sizes (~344px width). 
image

**Comment by evening** [comment]
hmm tbh i dont know best practices for it, i think as long as it looks good on an iphone se ([640px](https://screensiz.es/))

**Review by evening — APPROVED** [review]
LGTM!

**Pull request merged**
